### PR TITLE
DBus activation support

### PR DESCRIPTION
**Pull request by jbeich**
Allow Secret Service API consumers to auto-start pass-secrets.

Example usage:
```
$ dbus-send --print-reply --session --type=method_call \
  --dest=org.freedesktop.DBus / org.freedesktop.DBus.ListActivatableNames
method return time=12345.67890 sender=org.freedesktop.DBus -> destination=:1.0 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus" (dbus-daemon)
      string "org.freedesktop.Notifications" (mako)
      string "org.freedesktop.secrets" (pass-secrets)
   ]

$ pgrep pass || echo Exit $?
Exit 1

$ secret-tool store --label=test foo bar
Password:
dbus-daemon[1111]: [session uid=1001 pid=1111] Activating service name='org.freedesktop.secrets' requested by ':1.1' (uid=1001 pid=2222 comm="secret-tool store --label=test foo bar")
dbus-daemon[1111]: [session uid=1001 pid=1111] Successfully activated service 'org.freedesktop.secrets'
Found pass at /usr/local/bin/pass
/home/foo/.password-store/secretservice/<hash>/<hash>

Enter contents of secretservice/<hash>/<hash>/secret and press Ctrl+D when finished:

$ pgrep pass || echo Exit $?
3333
```

### CODE REVIEW

**Comment by nullobsi** [comment]
Thanks for the PR.

I'll merge this as soon as I have the time to make sure the AUR makepkg works

**Comment by jbeich** [comment]
> make sure the AUR makepkg works

I think, that would only test build. Do you mean runtime instead: systemd activation vs. dbus activation?

**Comment by jonassmedegaard** [comment]
@nullobsi Any news on looking into this?

**Comment by nullobsi** [comment]
It's been merged and pushed to the AUR. I believe it should be fine now.

**Pull request merged**
